### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sxzz** [rolldown/tsdown#52]
- [x] rollup types #50 
- [x] workspace support for better performance #44
- [ ] zero config (preset)

## Integration

- [x] [unplugin](https://github.com/unjs/unplugin/compare/main...tsdown)
- [x] [Vue Macros](https://github.com/vue-macros/vue-macros) - Needs #44
- [x] [Vue Vine](https://github.com/vue-vine/vue-vine)

**Comment by sxzz** [comment]
unbuild is another excellent build tool, offering features similar to tsup/tsdown. You should consider choosing one of them based on your needs.

**Comment by Wyatex** [comment]
Hope to create a template repository, such as [unjs/template](https://github.com/unjs/template)

**Comment by sxzz** [comment]
@Wyatex https://github.com/sxzz/ts-starter
